stages:
  - test
  - docker

test:
  stage: test
  image: python
  services:
    - postgres:latest
  variables:
    DATABASE_URL: 'postgresql://postgres:postgres@postgres:5432/postgres'
    POSTGRES_DB: postgres
    POSTGRES_USER: postgres
    POSTGRES_PASSWORD: postgres
  before_script:
    - pip install pipenv
    - pipenv install --system
    - python beez/manage.py collectstatic --no-input
  script:
    - python beez/manage.py test api

docker:
  stage: docker
  image: docker
  services:
    - docker:dind
  variables:
    DOCKER_DRIVER: overlay2
  only:
    - tags
  script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN registry.gitlab.com
    - docker build $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG .
    - docker tag $CI_REGISTRY_IMAGE latest
    - docker push $CI_REGISTRY_IMAGE

